services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    networks:
      - inception-network
    env_file: 
      - .env
    # restart: on-failure
    depends_on: 
      - wordpress

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    ports:
      - 9000:9000
    networks:
      - inception-network
    env_file: 
      - .env
    # restart: on-failure
    depends_on: 
      - mariadb
    volumes:
      - wordpress_db:/var/www/html

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    ports:
      - 3306:3306
    networks:
      - inception-network
    env_file: 
      - .env
    # restart: on-failure
    volumes:
      - mysql_db:/var/lib/mysql

networks:
  inception-network:
    driver: bridge

volumes:
  wordpress_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ynoujoum/data/wordpress_db
  mysql_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ynoujoum/data/mysql_db